import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="home-page">
          <div className="side-bar">
            <img src="img/logo.png" alt="" />
            <p>
              Copyright © 2022 <Link href="/">Teameverywhere</Link> Co. All
              rights reserved.
            </p>
          </div>
          <div className="main-bar">
            <h1>MINDS AI</h1>
            <h1>WEB APPLICATION</h1>
            <h3>ADMIN APP STORYBOARD</h3>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
